// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDBBntAJcmjvJ4QB0tan1iu2WI8Bw4aE',
    appId: '1:406446535404:web:a398404498f86b17a7ebc9',
    messagingSenderId: '406446535404',
    projectId: 'schaibleapp',
    authDomain: 'schaibleapp.firebaseapp.com',
    storageBucket: 'schaibleapp.firebasestorage.app',
    measurementId: 'G-Q6Z7TMJ66L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxexGXnZCEj90t3wz9nEJrEoY5K3VDF74',
    appId: '1:406446535404:android:e7d2da5cbad28b2fa7ebc9',
    messagingSenderId: '406446535404',
    projectId: 'schaibleapp',
    storageBucket: 'schaibleapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_SYB8CXk0gOiim2wUUnHNw63QebWdOLg',
    appId: '1:406446535404:ios:ab39ba4daa299a1ca7ebc9',
    messagingSenderId: '406446535404',
    projectId: 'schaibleapp',
    storageBucket: 'schaibleapp.firebasestorage.app',
    iosBundleId: 'com.schaible.saegewerke.schaible',
  );
}
